-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("BufReadPost", {
--   pattern = "*",
--   callback = function()
--     vim.cmd([[ e ++ff=dos ]]) -- Reload as DOS format if needed
--     vim.bo.fileformat = "unix" -- Set the fileformat to unix
--   end,
-- })
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*",
--   callback = function()
--     vim.cmd([[ %s/\r//g ]])
--   end,
-- })
