-- local mappings = require("telescope.mappings")
return {
  --   "rest-nvim/rest.nvim",
  --   dependencies = {
  --     "nvim-treesitter/nvim-treesitter",
  --     opts = function(_, opts)
  --       opts.ensure_installed = opts.ensure_installed or {}
  --       table.insert(opts.ensure_installed, "http")
  --     end,
  --   },
  --   config = function()
  --     -- require("telescope").load_extension("rest")
  --     require("rest-nvim").setup({
  --       result = {
  --         show_headers = true,
  --         show_cookies = true,
  --         split_horizontal = false,
  --         split_in_place = false,
  --         format = "json",
  --         format_command = "jq .",
  --       },
  --       highlight = {
  --         enabled = true,
  --         timeout = 150,
  --       },
  --       --   defaults = {
  --       --     mappings({
  --       --       i = {},
  --       --     }),
  --       --   },
  --     })
  --   end,
}
